### ISSUE TITLE
"You are not in Draft Mode or in the Visual Editor"

### ISSUE THREAD

**Issue by wiledal** [storyblok/storyblok-react#156]
<img width="713" alt="Screenshot 2022-07-27 at 15 48 18" src="https://user-images.githubusercontent.com/1035169/181263396-286661c9-be3f-4115-b569-980b622cce7c.png">

What's the point of this warning? Looking at the code, it just checks that the `window.location === window.parent.location`.
I don't care if we are not in "Draft mode", the page should display in any case.

This warning is cluttering up our console in both development and production environments.

Are you suggesting we should _not_ use `useStoryblokState` if outside the visual editor? It's not smooth to make React hooks conditional.

**Comment by fgiuliani** [comment]
Hi @wiledal! Thanks for your comment.

The idea of the message is not loading the Storyblok Bridge if you are outside the Visual Editor, or working with the Published Mode.

`useStoryblokState` has a `preview` parameter, where you can define if you are in a preview environment or not:
https://github.com/storyblok/storyblok-react/blob/feature/v1/lib/index.ts#L56

Does this work for you?

**Comment by wiledal** [comment]
Hey, @fgiuliani, thanks for your reply.

I suppose using that parameter will suppress the message in production, but it still clutters our dev environments.
Looking at the code, I'm under the impression that this message shows every time it does not load the bridge.

I'm happy that the bridge isn't loaded, that seems to work fine, but I wish it wouldn't spam my console :)

<img width="697" alt="Screenshot 2022-07-27 at 21 50 07" src="https://user-images.githubusercontent.com/1035169/181359722-ca4b3847-a120-4da8-84cf-a3d86140aeb2.png">

**Comment by fgiuliani** [comment]
Hey @wiledal thanks for your message.
The code that is triggering the warning is in `@storyblok/js`, a dependency of this package:

https://github.com/storyblok/storyblok-js/blob/3932d6eaa5dd04892ceb4a75962a1552cbce8f38/lib/modules/bridge.ts#L10

Are you setting `bridge: false` in the `storyblokInit` function when you are outside of the Visual Editor?

**Comment by wiledal** [comment]
Hmm, our init function happens outside of the React context, naturally, as it is used by both serverside and clientside operations, and we are unaware of the preview state at the moment of initiation, since the preview state (`version: 'draft'`) is handled during the fetch with `storyblokApi`.

I suppose we can do `storyblokInit({bridge: false})`, and then call `useStoryblokBridge()` at a later stage, when we know we want it -- however that means we'd need to detect the editor manually which you are clearly already doing, hence the warning.

It makes more sense to me that the bridge would not initiate automatically if it cannot be utilised.

(Also, why is `useStoryblokBridge` named that way, it's not a React hook. Seems like the naming conventions are a bit scattered. A name like `storyblokBridgeInit` would follow the same pattern as your other methods and not interfere with React standards)

**Comment by wiledal** [comment]
<img width="861" alt="Screenshot 2022-07-28 at 08 58 21" src="https://user-images.githubusercontent.com/1035169/181441137-74d02249-b5e9-4bbf-80c4-157bb1e15232.png">

This sentence does not make sense in the Storyblok context. You'd most likely never want to "disable the bridge on production".
Since Storyblok is a headless CMS, meaning you'd want to preview content on any environment, which includes production, staging, local environments.

The only reason why the bridge would be unwanted is if it does not do anything and only adds to the kb budget.

It's still unclear to me how we can avoid boilerplate gymnastics in order to get the desired effect:
- Load bridge only when its needed
- Environment agnostic

I guess we'll have to make a lazy api-getter function that initiates Storyblok late which also uses a method (probably the same method as you do in storyblok-js) to check for the possible editor-scenario.

**Comment by wiledal** [comment]
Ok, the answer was quite simple. Use the same check as the library does for displaying the warning message, and apply it to the bridge parameter.

```tsx
const shouldUseBridge =
  typeof window !== 'undefined'
    ? window.location !== window.parent.location
    : false

export const storyblok = storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_STORYBLOK_ACCESS_TOKEN,
  bridge: shouldUseBridge,
  use: [apiPlugin],
})

export const storyblokApi = getStoryblokApi()
```

This seems to work alright.

**Comment by wiledal** [comment]
> Are you setting `bridge: false` in the `storyblokInit` function when you are outside of the Visual Editor?

Please provide examples of how this is supposed to be achieved in the documentation 👆😄 
(or better yet, make the library do this automatically and let us override the setting if anyone should ever want to)

**Comment by wiledal** [comment]
<img width="548" alt="Screenshot 2022-07-28 at 10 49 12" src="https://user-images.githubusercontent.com/1035169/181463765-a0390c44-1a8e-4d90-bef4-40d877e330e1.png">

And now this happens?

**Comment by wiledal** [comment]
<img width="470" alt="Screenshot 2022-07-28 at 10 50 06" src="https://user-images.githubusercontent.com/1035169/181463965-7e8bca56-a43a-45f1-8388-4cad10923627.png">

Ok, now this happens.

**Comment by wiledal** [comment]
Unfortunately both `@storyblok/js` and `@storyblok/react` are inadequate for use to me in their current state due to their limited bridge loading capabilities.

The only way I can see this working is by rolling your own bridge loader, and your own state manager for editor events.

This was how we had it before using the old `storyblok-js-client`. I was hoping that these new libraries would alleviate some of the boilerplate, but the current state does not solve anything, and just adds sugar for component rendering, which I won't be using in  any of my advanced apps anyways.

The docs in this library suggest you can use `new window.StoryblokBridge()`, but we cannot be certain that the script is loaded, and the docs do not specify a way of listening for that event.

---

Here's how I ended up solving it:
1. Check for "editor like"-conditions using window.location, load the bridge, and initiate a single instance
2. In my page component, listen to the bridge loading, then bind the events (currently there is no way to unbind events in the bridge (https://github.com/storyblok/storyblok-js/issues/99), which is also a problem for React as all effects should be symmetrical)

<img width="681" alt="Screenshot 2022-07-28 at 12 36 31" src="https://user-images.githubusercontent.com/1035169/181485952-4916682b-39b8-4ab4-913e-26958b1f1c7d.png">

<img width="639" alt="Screenshot 2022-07-28 at 12 40 51" src="https://user-images.githubusercontent.com/1035169/181486629-a782bc74-fd36-4945-821f-4ab0801f3568.png">

Since we cannot unbind events, we cannot verify that the updated page corresponds to the current content being updated, which is a blocking issue on advanced pages with multiple editable stories visible at the same time. This is not an unlikely scenario at all.

**Comment by sendy34** [comment]
thanks @wiledal this solution works great!

**Comment by fgiuliani** [comment]
Hey @wiledal @sendy34 thanks for your input, for testing the SDK, working with it, and providing feedback about it.
We, Storyblok's DevRel team, are willing to improve the SDKs and the tools provided to the developers, and the community feedback is super helpful and more than welcome.

Do you think your code and ideas can be included in the SDK? So it can support more custom scenarios and make the work easier for the developers. Pull Requests are more than welcome, and Storyblok's DevRel team will appreciate that.

**Comment by wiledal** [comment]
Hey @fgiuliani, 

For sure, I could contribute, but seeing as these issues stretch across 2 open source and 1 closed source project, it's a bit of a hassle.

Turns out this package didn't actually provide anything useful to me, so I'm back to using `@storyblok/js` with a custom bridge loader.

There are a few problems:
- `useStoryblokBridge` is named as, and used as, a React hook, but is not a React hook.
- `useStoryblokState` always throws a warning, or an error, depending if the bridge is loaded or not loaded (because `useStoryblokBridge`)
-  The bridge itself doesn't allow us to unbind from event handlers, making it incompatible with React effects, and problematic in general

---

In order for us to use Storyblok in an SSR Next.js setup, we:
- Use @storyblok/js, with `bridge: false`
- Use a custom asynchronous bridge loader, which waits for the loading to finish before initiating dependent listeners (and only in an editor-like scenario)
- Use a custom Event Emitter that allows us to unbind events, serving as a proxy in front of the StoryblokBridgeV2's _always on_ events (to allow us mounting and unmounting story listeners without causing React memory leaks)
- Use a custom hook and state handler using the bridge loader and the event emitter, where the story is always accessible the same way even if it wont update `const story = useStoryState(initialStory)`. Using hooks conditionally in React is not possible (https://reactjs.org/docs/hooks-overview.html#rules-of-hooks), so the hook itself must contain the conditional logic.

**Comment by fgiuliani** [comment]
Thank you for the insights @wiledal. If you can share some code on how you are solving your scenario, with the steps you described in the message above, that would be super helpful to see how we can improve the React SDK and other SDKs we maintain at Storyblok.

**Comment by Pandan** [comment]
Any progress/updates on the issues @wiledal are describing?
I am also experiencing the problem with useStoryblokState when bridge is disabled.  
Also getting warnings in the visual editor, saying "Story ID is not defined. ..." 

As @wiledal is saying, the desired solution would be to just initiate Storyblok and have everything taken care of.

**Comment by fgiuliani** [comment]
Hello @Pandan @samlof 
`useStoryblokState` has a parameter called preview:
https://github.com/storyblok/storyblok-react/blob/main/lib/index.ts#L62

 If you set it to false, you shouldn't get the warning outside of the Visual Editor:

```
  let sbParams = {
    version: "draft",
  };

  story = useStoryblokState(story, sbParams, false);
```

Can you confirm that's what you are doing? Or what's exactly the issue you are having?

**Comment by fgiuliani** [comment]
Hello everyone,
We just released Storyblok React SDK v2.0.0:
https://github.com/storyblok/storyblok-react/releases/tag/v2.0.0

With this PR we're removing the `axios` dependency. You don't need to install it anymore in order to use the Storyblok React SDK.
We are also adding other changes and fixes:
https://github.com/storyblok/storyblok-react/pull/345

Your feedback is appreciated

**Comment by konsti** [comment]
This is still not working in the newest version if this library. You also removed the `preview` parameter of `useStoryblokState`.
Any advice?

**Comment by fgiuliani** [comment]
Hi @konsti thanks for your feedback. Can you share with us some steps to reproduce the issue you are having?

We're working on updating the docs about having removed the `preview` parameter. The idea is basically enabling or disabling the preview based on the value of the `bridge` parameter sent when initializing the Storyblok connection using `storyblokInit`
https://github.com/storyblok/storyblok-react#initialization
