### ISSUE TITLE
resolveRelations Not Working Correctly in useStoryblokState

### ISSUE THREAD

**Issue by grez96** [storyblok/storyblok-react#361]
Greetings, I have some components that I would like to reuse between multiple pages (Nav/Footer).  I structured my Storyblok content using the following tutorial: https://www.storyblok.com/tp/global-components-references for creating global component references.

I initially fetch my first story using:
```
const story = getStoryblokApi().get(`cdn/stories/${slug}`, { resolve_relations: 'global-reference.reference' })
```

At this point the references have been converted correctly and if I load my space inside of Storyblok CMS everything works correctly.

I am then using `useStoryblokState` for bridging, and passing the `resolveRelations` parameter for converting the reference string uuid to JSON data:
```
useStoryblokState(story, {
  resolveRelations: ['global-reference.reference']
});
```

If I then attempt to make a content change inside of Storyblok CMS I receive a 401 error in the console:
<img width="562" alt="Screen Shot 2022-12-27 at 3 19 11 PM" src="https://user-images.githubusercontent.com/42558504/209718902-150add99-67ad-4033-8fcf-1e16f8412fc7.png">
And storyblok cms logs me out and I have to log back in.

I guess this is happening because passing the resolveRelations parameter to useStoryblokState attempts to retrieve data from v1 API whereas my space is using the v2 API.  I am looking for a solution that allows me to convert the reference string uuid to JSON data correctly. Please let me know if I am approaching this incorrectly.

My environment is NextJS with dependency `"@storyblok/react": "2.0.0"`. My Storyblok space was made in the US region and I believe it is on V2 (by default?)

**Comment by grez96** [comment]
Can confirm that this seems to be an issue only with spaces created in the US region. I have replicated the above setup in EU region and everything works well.

**Comment by guanacone** [comment]
Not sure if my issue is directly related to this one, but I'm experiencing a similar problem. `useStoryblok()` is not resolving relations
```
./_app.tsx

...
storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN,
  use: [apiPlugin],
  apiOptions: { resolveNestedRelations: true }
});
...

./[slug]

...
sbStory = useStoryblok(
      story.full_slug,
      {
        version: 'draft',
        language: locale,
        resolve_links: 'url',
        resolve_relations: 'author,category'
      },
    );
  }
...
```

response:
![Screenshot from 2022-12-28 09-36-00](https://user-images.githubusercontent.com/11678477/209836083-3bc5c1c5-b4c2-461c-8f41-b296d7e8176e.png)

In the gapi playground the fields `author` and `category` get resolved without having to provide `resolve_relations`. 
`https://api.storyblok.com/v2/cdn/stories/blog/learn-to-sail-online-in-4-steps?resolve_relations=author,category&token=MY_TOKEN` will return the resolved relations in the `rel` field.

**Comment by iamfortune** [comment]
Hi @grez96, We've made a fix that will be merged in the coming days. Thanks for bringing this to our attention.

**Comment by fgiuliani** [comment]
Hi @grez96! 
We released a new version of the React SDK that should solve your issue. Could you check if it works for you?

**Comment by grez96** [comment]
I have upgraded to `"@storyblok/react": "2.0.3"` and the issue still persists with me receiving the same 401 unauthorized error. This only seems to happen to spaces created in the US region. The exact same setup but in the EU region produces a 200.

![Screen Shot 2023-01-05 at 11 15 00 PM](https://user-images.githubusercontent.com/42558504/210928984-30514a6c-cacc-49eb-a962-a9e70213e7bc.png)

Are you able to point me to the PR that solved this issue?
Please let me know if I can assist you guys in any way. Really appreciate the support on this issue.

**Comment by fgiuliani** [comment]
@grez96 have you added the "region" parameter when calling storyblokInit function?
https://github.com/storyblok/storyblok-react#initialization

**Comment by grez96** [comment]
Yes I do pass the region parameter:
```
storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_STORYBLOK_ACCESS_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    region: 'us'
  },
  components
});
```
This allows my initial fetch to succeed:
```
const story = getStoryblokApi().get(`cdn/stories/${slug}`, { resolve_relations: 'global-reference.reference' })
```

but after bridging
```
useStoryblokState(story, {
  resolveRelations: ['global-reference.reference']
});
```

and subsequently updating content from within storyblok, that's when I recieve the 401.

**Comment by MRued** [comment]
Missing resolved relations for global components occur for me as well on @storyblok/react `> 2.0.0` versions. 

Currently trying `v2.0.6` and the relations are not resolved and I get an array of UUIDs, but if I downgrade to `<2.0.0` like `1.9.3`, the relations are resolved as expected and I get an array containing all the data from those relations.  
I am using the EU region.

I have this global component that I use on several stories (pages). That global component contains a multi-options field where I select several other pages. Maybe it happens because it first has to resolve from `global -> block` and then from `block -> multi-options field relations`, but I am not sure. 

@fgiuliani Hope this information helps in any way.

**Comment by fgiuliani** [comment]
Hey @grez96 we've been discussing with the team thinking about possible reasons for the error you are getting. Can you share with us a reproducible demo of your code, so we can download it and reproduce the error on our end?

**Comment by fgiuliani** [comment]
Hey @MRued thanks for your message. We've been discussing with the team about your issue, and I think it's different from the one originally reported.
Can you share with us more details? Like a code sample or a reproducible demo of your code, so we can take a deeper look?
Feel free to create a separate GitHub issue if you prefer, so we can keep track of the issues separately.

**Comment by MRued** [comment]
Hi @fgiuliani 

I have created a separate issue here ([issue 395](https://github.com/storyblok/storyblok-react/issues/395)) with more information and steps to reproduce.

Let me know if you need more information

**Comment by GFier** [comment]
Hi! 

Having the same issue. Getting 401 error when adding resolveRelations to useStoryblokState but works correctly in the first server-side fetch using getStoryblokApi().

Version: 2.0.13, Region: US.
Request URL: https://app.storyblok.com/v1/cdn/stories?by_uuids=c80b1f24-01cb-4558-bb1a-16664713339f&version=draft&language=&token=MY-TOKEN&resolve_relations%5B%5D=globalHeader.header&region=us-east-1 

Any news about this problem??

**Comment by smol-honk** [comment]
I'm also getting the same issue as @GFier

**Comment by fgiuliani** [comment]
Hello everyone!
We just released a new version of the React SDK with some changes that should fix the issues related to resolving relations. Can you check if everything works as expected with the latest version of the SDK?
@MRued @GFier @smol-honk

**Comment by RyanMulready** [comment]
The updates definitely resolved https://github.com/storyblok/storyblok-react/issues/395 but the issue around `401` errors on `us` regions seemingly still exists. Tested and confirmed on our space this morning.

**Comment by fgiuliani** [comment]
Hi @RyanMulready thanks for your message.
Are you defining the region when calling the storyblokInit function?
https://github.com/storyblok/storyblok-react#initialization

Do you have a way of sharing a reproducible demo of your code, so we can download it and reproduce the error on our end?

**Comment by fgiuliani** [comment]
Hi @RyanMulready thanks for sharing. Will communicate with the Product team at Storyblok and keep you updated.

**Comment by RyanMulready** [comment]
> Hi! Same for me, updated to the latest version and still getting 401 Unauthorized error.

We have a work around; though we are obviously not going to ask our content team to do this.

- Install the greesemonkey or tampermonkey browser extension.
- add a custom user script:
```js
// ==UserScript==
// @name     storyblok 401 workaround
// @version  1
// @grant    none
// @include  https://app.storyblok.com/*
// ==/UserScript==

unsafeWindow.STORYBLOK_API_ENDPOINT = 'https://api-us.storyblok.com';
```

**Comment by fgiuliani** [comment]
Hello everyone,
We just pushed a change to the Storyblok application which should fix the issue. Can you reload the Storyblok app and check if it's working properly for you now?

@RyanMulready @GFier @MRued

**Comment by grez96** [comment]
Great job Storyblok team! Resolve relations is now working correctly on the US space. :D

**Comment by RyanMulready** [comment]
> Hello everyone, We just pushed a change to the Storyblok application which should fix the issue. Can you reload the Storyblok app and check if it's working properly for you now?
> 
> @RyanMulready @GFier @MRued

Can confirm now resolved for us as well. Appreciate the updates 🔥
