### ISSUE TITLE
resolveRelations are not working correctly after updated to v2

### ISSUE THREAD

**Issue by MRued** [storyblok/storyblok-react#395]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

resolveRelations does not work correctly in some cases when resolving a list of relations on a global component..

---

## Expected Behavior
@storyblok/react should resolve Relations correctly on global components with a relation field to several other pages.

## Current Behavior
In @storyblok/react `> v2.0.0` the relations are not resolved correctly, meaning that only an array of UUIDs are returned, and not the array populated with pages data.

## Steps to Reproduce
1. Download the repo I have linked to below
2. run npm install and run the project locally
3. Go to `/services/service-page-1` or `/services/service-page-2` path and see the displayed array (only uuids).
4. Downgrade to @storyblok/react `v1.3.5` and go to the same paths. Now the array contains info of the relationed pages.

[Source code for reproducing](https://github.com/MRued/storyblok-react-resolverelation-issue)

**Comment by fgiuliani** [comment]
Hey @MRued thanks for sharing the details, insights, and the repo for reproducing the issue. 
One last request for you: Can you share the JSON object that represents the story `service-page-1` or `service-page-2`, or a screenshot from Storyblok, in order to see how the relation is being defined?

We're already taking a look at your issue

**Comment by MRued** [comment]
Of course!

The story object for a service page is:
```js
{
  story: {
    name: "Service page 1",
    created_at: "2023-01-27T13:36:24.090Z",
    published_at: "2023-01-27T14:40:07.674Z",
    id: 253557551,
    uuid: "824f13bb-b5ff-405f-a2c6-0e4e030dc76c",
    content: {
      cta: "",
      _uid: "5960ea7f-c526-494d-a188-e954a80d909f",
      body: [
        {
          _uid: "764ee4f2-b8eb-424f-adc8-f4cc9bf425d7",
          component: "Global",
          globalref: "aa0f199e-9c53-4f8d-bc6b-0a2ee48d0101",
          _editable:
            '<!--#storyblok#{"name": "Global", "space": "193687", "uid": "764ee4f2-b8eb-424f-adc8-f4cc9bf425d7", "id": "253557551"}-->',
        },
      ],
      faqs: [],
      Title: "",
      logos: [],
      title: "",
      bg_image: {
        id: null,
        alt: null,
        name: "",
        focus: null,
        title: null,
        filename: "",
        copyright: null,
        fieldtype: "asset",
      },
      darkmode: false,
      iconName: "ChartPieIcon",
      subtitle: "",
      component: "page",
      HreflangDA: {
        id: "",
        url: "",
        linktype: "story",
        fieldtype: "multilink",
        cached_url: "",
      },
      HreflangEN: {
        id: "",
        url: "",
        linktype: "story",
        fieldtype: "multilink",
        cached_url: "",
      },
      HreflangNO: {
        id: "",
        url: "",
        linktype: "story",
        fieldtype: "multilink",
        cached_url: "",
      },
      HreflangSV: {
        id: "",
        url: "",
        linktype: "story",
        fieldtype: "multilink",
        cached_url: "",
      },
      meta_title: "Insights - markedsledende indsigter.",
      Description:
        "For at lægge en markedsledende strategi kræver det markedsledende indsigter. ",
      button_link: "",
      button_text: "",
      animated_shape: false,
      meta_description:
        "Ved at have et godt billede af jeres startposition, kan vi nemmere afklare, hvordan vi får jer over målstregen.",
      _editable:
        '<!--#storyblok#{"name": "page", "space": "193687", "uid": "5960ea7f-c526-494d-a188-e954a80d909f", "id": "253557551"}-->',
    },
    slug: "service-page-1",
    full_slug: "da/services/service-page-1",
    sort_by_date: null,
    position: 0,
    tag_list: [],
    is_startpage: false,
    parent_id: 253557218,
    meta_data: null,
    group_id: "65ec5ab2-8cc5-48e1-a012-185dd43805ea",
    first_published_at: "2022-11-16T08:35:56.176Z",
    release_id: null,
    lang: "default",
    path: null,
    alternates: [],
    default_full_slug: null,
    translated_slugs: null,
  },
  cv: 1674830407,
  rels: [],
  links: [],
};
```

the global component json
```js
{
  story: {
    name: "sidebar",
    created_at: "2023-01-27T14:38:29.686Z",
    published_at: "2023-01-27T14:38:47.800Z",
    id: 253576055,
    uuid: "aa0f199e-9c53-4f8d-bc6b-0a2ee48d0101",
    content: {
      _uid: "e8f880e6-df3f-4528-90ea-87b18aca5c38",
      pages: [
        "824f13bb-b5ff-405f-a2c6-0e4e030dc76c",
        "20156ffe-f392-485f-9775-ece4da3802ed",
        "9b47b5a4-1ab6-41b9-a3a6-337bfdd96ee3",
      ],
      title: "The global sidebar component that contains links to other pages",
      component: "ServicSidebar",
      _editable:
        '<!--#storyblok#{"name": "ServicSidebar", "space": "193687", "uid": "e8f880e6-df3f-4528-90ea-87b18aca5c38", "id": "253576055"}-->',
    },
    slug: "sidebar",
    full_slug: "global/shared-components/da/sidebar",
    sort_by_date: null,
    position: -50,
    tag_list: [],
    is_startpage: false,
    parent_id: 253557644,
    meta_data: null,
    group_id: "44ccc516-e192-49cf-a965-469257267508",
    first_published_at: "2023-01-27T14:38:47.800Z",
    release_id: null,
    lang: "default",
    path: null,
    alternates: [],
    default_full_slug: null,
    translated_slugs: null,
  },
  cv: 1674830407,
  rels: [],
  links: [],
};
```


Screenshots of service-page-1
![Xnip2023-02-06_10-04-58](https://user-images.githubusercontent.com/28734013/216930258-0f184304-2246-440e-8464-da8fb1b09c60.png)

![Xnip2023-02-06_10-05-25](https://user-images.githubusercontent.com/28734013/216930240-ebb1a2ca-2140-4bab-90ec-5dfed1eb568b.png)

![Xnip2023-02-06_10-05-38](https://user-images.githubusercontent.com/28734013/216930226-afef9200-2052-47db-9d00-f9debc859d31.png)

![Xnip2023-02-06_10-09-35](https://user-images.githubusercontent.com/28734013/216930989-d67aeaaa-6539-4bbe-b5e7-f0a2ae7102dc.png)

**Comment by fgiuliani** [comment]
Hi @MRued sorry for all the back and forth. We're struggling to try to replicate the issue as it is working on our end when we test it.

Could you share with us the ID of the space you are using on your project?

**Comment by MRued** [comment]
@fgiuliani of course!

spaceID: `193687`
You can run the repo locally and you should experience the issue when switching @storyblok/react version

**Comment by fgiuliani** [comment]
Hi @MRued! The team is still taking a look at the issue. We didn't find the problem yet, so we'll keep investigating

**Comment by jon301** [comment]
Any news about the investigation ?
I am having the exact same issue 😔

**Comment by fgiuliani** [comment]
Hello everyone!
We just released a new version of the React SDK with some changes that should fix the issues related to resolving relations. Can you check if everything works as expected with the latest version of the SDK?

@MRued @jon301

**Comment by MRued** [comment]
The new update (v2.0.16) works for me!
Thanks for solving the issue @fgiuliani

**Comment by jon301** [comment]
Works for me too ! 
Thanks @fgiuliani 🙏

**Comment by fgiuliani** [comment]
Amazing! Good to know 😄 
Closing this issue as the original problem was solved.

**Comment by petr166** [comment]
@MRued are you getting the relations resolved in `story.content` or just included in `response.data.rels`?? 

Referencing [my comment in a different issue](https://github.com/storyblok/storyblok-js-client/issues/416#issuecomment-1473621018)

**Comment by MRued** [comment]
Not 100% sure what you mean @petr166, but I would say `story.content`.. I am using it in a NextJS app where I have a page with a component relation. And that relation I am reffering to, has an array of relations to other pages. The relations are resolved in the _app.tsx file (following this demo [repo](https://github.com/storyblok/nextjs-multilanguage-website))

It didn't work before the recent update but now it works perfectly

**Comment by petr166** [comment]
In your shared example [here](https://github.com/storyblok/storyblok-react/issues/395#issuecomment-1418744872) the global component has `story.content.pages = string[]`; pages is an array of story IDs instead of being resolved to the story objects. I'm asking if this was fixed for you with the library update. 
For me, `rels` (which was empty in your example) is populated with resolved stories, but `content` only has story IDs still

**Comment by MRued** [comment]
@petr166 It was fixed in the update to the latest version. Previously I had an array of story IDs as in the example, but now I have an array of resolved story objects (which I also had in version < 2.0.0)

Not sure why rels is empty in my example

**Comment by petr166** [comment]
Thanks for confirming @MRued; i'll open another issue as the problem persists for me

**Comment by Jimmy378** [comment]
Did you get a resolution @petr166? Problem persists for me as well on `2.0.18`. I can see the stories in `rels` but only IDs in content.

**Comment by mdunbavan** [comment]
Hello,

I am facing the same issue here. My code is below for an example:

```
const fetchStudentStoriesData = async () => {
      await api
        .get("cdn/stories", {
          version: "published",
          starts_with: "university/student-stories/",
          resolve_relations: ["student_story_course"],
        })
        .then((resp) => resp.data)
        .then((response) => {
          setStudentStories(response.stories);
          setStudentStoryCats(response.rels);
        });
    };
```
I'm having to set relationships outside which is fine to me but I need specific meta info from a relationship to be added onto the card such as the relationship category name that sits on the card itself.

Is there a workaround for it anywhere?

Thanks,
Mark

**Comment by petr166** [comment]
@Jimmy378 nothing yet; temporarily (i hope) i'm manually setting the data on `content` from `rels`

- [comment from a different issue](https://github.com/storyblok/storyblok-js-client/issues/416#issuecomment-1527539542)

**Comment by mdunbavan** [comment]
@petr166 definitely not working for me on next 13.2.4 and storyblok/react ^2.0.19.
