### ISSUE TITLE
RSC Typeings for getStoryblokApi() broken, all methods have any as type

### ISSUE THREAD

**Issue by carlonoelle** [storyblok/storyblok-react#582]
### Describe the issue you're facing

The type of `const storyblokApi = getStoryblokApi();` is correctly StoryblokClient, but the resolution of the methods is broken.

All methods have `any` as type, not very usefull. I followed another issue saying for RSC types to work you have to change out `moduleResolution` in tsconfig.json to `node16`. After that the rsc import gets picked up by tsserver, but still no methods.

<img width="589" alt="image" src="https://github.com/storyblok/storyblok-react/assets/13131183/d9b1408b-889b-44c0-a64b-3f0cd1b009ac">

Does someone else also experience this?

### Reproduction

https://github.com/storyblok/storyblok-react/tree/main/playground-next13-rsc

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 639.28 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by fgiuliani** [comment]
Hi @carlonoelle thanks for your report.

I'm trying to replicate the issue using the `playground-next13-rsc` from the SDK repository, and it looks like working correctly for me.
Do you have any other detail or step that can help us to reproduce the issue?

![Screen Shot 2023-06-20 at 16 06 46](https://github.com/storyblok/storyblok-react/assets/464646/f0c68cd5-18f9-4e3e-b643-52ae96b277eb)
![Screen Shot 2023-06-20 at 16 06 55](https://github.com/storyblok/storyblok-react/assets/464646/8f637202-0a2b-4579-a4b1-ef2eec6315ea)

**Comment by sbuys** [comment]
I am having the same issue.

Steps to reproduce:

- Create a new next app using create-next-app
- Add import statement ➡️ `import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";`

**Comment by fgiuliani** [comment]
@carlonoelle can you check if everything is ok? Or you have any way to share the scenario is not working for you?

**Comment by addemod** [comment]
I have a similar problem, but in my case the "rsc" folder is not typed at all:
![image](https://github.com/storyblok/storyblok-react/assets/2089319/8b0afb83-c8e9-4eee-90d3-d7b2e205ec0c)

If I change my tsconfig to use `moduleResolution: "NodeNext"`, I can import from /rsc, but then I get the same problem as OP:
![image](https://github.com/storyblok/storyblok-react/assets/2089319/cab4a1cd-d2f8-4579-a8ef-82e760bb484d)

I simply created a new NextJs project using "npx create-next-app@latest" and then installed @storyblok/react using "npm install @storyblok/react".

**Comment by fgiuliani** [comment]
Hi @addemod thanks for sharing details.

The method `getStory` is part of `StoryblokJSClient`:
https://github.com/storyblok/storyblok-js-client/blob/7dfdd54961add726c392738d6c962a08ed3d6dfd/src/index.ts#L271

That client is imported and later exported by the Storyblok React SDK:
https://github.com/storyblok/storyblok-react/blob/main/lib/types.ts#L45

I'm wondering if the issue is coming directly from the `storyblok-js-client` lib. I'll talk to the team and come back later.

**Comment by addemod** [comment]
A workaround is to declare the type in a declaration file
```ts
// storyblok-rsc.d.ts
declare module '@storyblok/react/rsc' {
  export * from '@storyblok/react';
}
```
and then include it in tsconfig.json:
```ts
"include": ["storyblok-rsc.d.ts", "next-env.d.ts", ......]
```

**Comment by fgiuliani** [comment]
@addemod I'm not sure I'm following what would that fix 🤔 I just tried and nothing happened

**Comment by addemod** [comment]
> @addemod I'm not sure I'm following what would that fix 🤔 I just tried and nothing happened

The workaround is from OP in this issue: https://github.com/storyblok/storyblok-react/issues/570#issue-1749276890.
Not really a fix, as you are typing everything in the `rsc` module to use the typing from `@storyblok/react`.

**Comment by fgiuliani** [comment]
Hello @carlonoelle @addemod!

We just released a new version of the React SDK that introduces some fixes we applied to storyblok-js-client.
https://github.com/storyblok/storyblok-react/releases/tag/v2.1.9

Can you check that types are working ok now for you?

**Comment by carlonoelle** [comment]
Hey @fgiuliani and all,

Sorry i didn't respond, wenz on holiday right after submitting the issue.

Will check out the updated js client, and share if it fixed my bugs.

**Comment by addemod** [comment]
@fgiuliani Sadly I still have the same problem. `/rsc` and `/bridge-loader` are showing the same error as before:
![image](https://github.com/storyblok/storyblok-react/assets/2089319/63c93794-0601-484c-afaf-0823d599925f)

I have `@storyblok/react` 2.1.9 installed. Also tried to forcefully install all packages again, `npm install --force`, still the same error.

**Comment by fgiuliani** [comment]
@addemod did you apply the change mentioned here?
https://github.com/storyblok/storyblok-react/issues/570#issuecomment-1591207805

The fix that was added was related to the StoryblokClient methods (get, getStory, etc). Is that working now for you?

**Comment by carlonoelle** [comment]
<img width="929" alt="image" src="https://github.com/storyblok/storyblok-react/assets/13131183/4edfb877-d252-4eaa-9150-5f6fd86632c9">

I could test it now, everything works for me. Only thing you have to do is setting `moduleResolution` to `nodenext` in your tsconfig, otherwise the import from `@storyblok/react/rsc` will show as unknown. I think this is your problem @addemod

**Comment by addemod** [comment]
@carlonoelle @fgiuliani My bad, I was confident that I already used `nodenext`, so I forgot to check it, but apparently I was still using `node`. It works as expected now :)

**Comment by carlonoelle** [comment]
Good to hear, will close this now
